/* list all the action types variable here, please put all the variables in its group only */

// user actions
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_INIT = 'FETCH_USER_INIT'

// login actions

export const LOGIN_INIT = 'LOGIN_INIT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

// login actions

export const USERDATA_INIT = 'USERDATA_INIT'
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS'
export const USERDATA_FAIL = 'USERDATA_FAIL'

// country list actions

export const COUNTRY_INIT = 'COUNTRY_INIT'
export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS'
export const COUNTRY_FAIL = 'COUNTRY_FAIL'

// segment list actions

export const SEGMENT_INIT = 'SEGMENT_INIT'
export const SEGMENT_SUCCESS = 'SEGMENT_SUCCESS'
export const SEGMENT_FAIL = 'SEGMENT_FAIL'

// delete segment actions

export const DEL_SEGMENT_INIT = 'DEL_SEGMENT_INIT'
export const DEL_SEGMENT_SUCCESS = 'DEL_SEGMENT_SUCCESS'
export const DEL_SEGMENT_FAIL = 'DEL_SEGMENT_FAIL'
// Admin
// consumer
export const FETCH_CONSUMER_INIT = 'FETCH_CONSUMER_INIT'
export const FETCH_CONSUMER_SUCCESS = 'FETCH_CONSUMER_SUCCESS'
export const FETCH_CONSUMER_FAIL = 'FETCH_CONSUMER_FAIL'
export const CREATE_CONSUMER_INIT = 'CREATE_CONSUMER_INIT'
export const CREATE_CONSUMER_COMPLETE = 'CREATE_CONSUMER_COMPLETE'
// call user list
export const CALL_USER_LIST = 'CALL_USER_LIST'

// Reward
export const FETCH_REWARD_INIT = 'FETCH_REWARD_INIT'
export const FETCH_REWARD_SUCCESS = 'FETCH_REWARD_SUCCESS'
export const FETCH_REWARD_FAIL = 'FETCH_REWARD_FAIL'
export const FETCH_REWARD_SAVEFORLATER = 'FETCH_REWARD_SAVEFORLATER'
export const FETCH_REWARD_SAVEFORLATER_DONE = 'FETCH_REWARD_SAVEFORLATER_DONE'
export const FETCH_REWARD_MORE = 'FETCH_REWARD_MORE'

export const FETCH_WALLET_INIT = 'FETCH_WALLET_INIT'
export const FETCH_WALLET_SUCCESS = 'FETCH_WALLET_SUCCESS'
export const FETCH_WALLET_FAIL = 'FETCH_WALLET_FAIL'
export const FETCH_WALLET_SAVEFORLATER = 'FETCH_WALLET_SAVEFORLATER'
export const FETCH_WALLET_SAVEFORLATER_DONE = 'FETCH_WALLET_SAVEFORLATER_DONE'
export const FETCH_WALLET_MORE = 'FETCH_WALLET_MORE'

// notifications
export const NOTIFICATION_INIT = 'NOTIFICATION_INIT'
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
export const NOTIFICATION_FAIL = 'NOTIFICATION_FAIL'
